# Generated by Django 6.0.3 on 2026-05-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='known_for_department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
