# Generated by Django 6.0.3 on 2026-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_rewatch',
            field=models.BooleanField(default=False),
        ),
    ]
