# Generated by Django 6.0.3 on 2026-05-31 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, help_text='Null means All-Time stats', null=True)),
                ('total_movies', models.IntegerField(default=0)),
                ('total_runtime', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('top_actors', models.JSONField(default=list)),
                ('top_directors', models.JSONField(default=list)),
                ('top_genres', models.JSONField(default=list)),
                ('decades', models.JSONField(default=dict)),
                ('languages', models.JSONField(default=list)),
                ('rating_distribution', models.JSONField(default=list)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
